# Empezar desde una imagen básica de Node.js
FROM node:16-alpine

# Crear y usar un directorio para la aplicación
WORKDIR /app

# Copiar los archivos de la aplicación en ese directorio
COPY . .

# Instalar las dependencias (cosas que necesita tu app para funcionar)
RUN npm install

# Exponer el puerto 3000 donde correrá la app
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]
